### ISSUE TITLE
No certs left

### ISSUE THREAD

**Issue by milky2028** [devguardio/carrier#8]
Hello!

First off, let me say that this product is super simple and super dope. My home machine is behind a double NAT scenario and this is a fantastic solution for SSH that doesn't involve me going through a whole thing to call my ISP and setup a static IP and all that jazz.

Secondly, I'm getting an error that says "access denied: no certs left" when I try to connect from one machine to another. I'm unsure of how figure this out. I was able to connect from my first machine to itself. Any help is much appreciated!

**Comment by aep** [comment]
happy to hear its useful to you :)

the side you want to connect to needs to know the identity of the side you're connecting from.

on machine A:

```
$ carrier identity
oX1Pvu9AA7VC.....
```


on machine B, open ~/.devguard/carrier.toml and add this section:

```
[[authorize]]
identity  = "oX1Pvu9AA7VC....."
resource = "*"
```

**Comment by milky2028** [comment]
Wow it works! What a dream! I was able to connect from my work Ubuntu machine to my Chromebook running Linux inside a container, which is pretty dope. It was, expectedly, a little laggy. I wonder if it might be possible to setup something similar to [mosh](https://mosh.org/) to reduce lag. Thanks again!

**Comment by aep** [comment]
great!

it should work fine on chromebook itself btw, without a container. We just don't have any official app, due to lack of chromebook. android is available too.

mosh does not support nat traversal, you'll have a hard time convincing it to build up a p2p session unless one side is open to the internet. you could run mosh on top of a carrier packet bridge to benefit from mosh's text prediction stuff. 

if you're behind double-nat, is is likely that carrier wasn't able to poke a hole either and is using the devguard.io proxy instead. The latest unreleased git code will tell you your connection properties (settled peering with "internet" or "proxy")

We do not operate proxies in the US, since we don't have any customers there. You'll be routed through a proxy in Frankfurt or Falkenstein, which may have suboptimal latency for you.
